export interface PartnerItem {
  id: string
  name: string
  category: string
  categoryAr: string
  sector: "marketing" | "tech" | "ai" | "system-integrator-cybersecurity" | "hub"
  relationshipType: "Official partner" | "Certified partner" | "Technology partner" | "Implementation platform" | "Integration" | "Vendor ecosystem"
  relationshipTypeAr: string
  description: string
  descriptionAr: string
  website: string
  featured?: boolean
  certificationLevel?: string
  verificationStatus: boolean
  tag?: string
}

export const PARTNERS_DATA: PartnerItem[] = [
  // ── MARKETING & BRANDING ECOSYSTEM ──────────────────────────────────────────
  {
    id: "meta-marketing",
    name: "Meta",
    category: "Advertising platforms",
    categoryAr: "منصات الإعلانات",
    sector: "marketing",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "منظومة تقنية وإعلانية معتمدة",
    description: "Paid social campaign management, Conversions API (CAPI) deployment, and audience scaling across Facebook & Instagram.",
    descriptionAr: "إدارة حملات التواصل الاجتماعي الممولة وربط واجهة برمجة التحويلات CAPI وتحسين الاستهداف.",
    website: "https://meta.com",
    verificationStatus: false,
  },
  {
    id: "google-marketing",
    name: "Google Ads & Analytics",
    category: "Analytics platforms",
    categoryAr: "منصات التحليل والتتبع",
    sector: "marketing",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "منظومة تقنية معتمدة",
    description: "Search, Display, Performance Max, and GA4 telemetry configuration with multi-touch attribution.",
    descriptionAr: "إعلانات البحث وشبكة العرض وإعداد أنظمة التحليلات GA4 ونماذج إسناد العائد المتعددة.",
    website: "https://ads.google.com",
    verificationStatus: false,
  },
  {
    id: "adobe-marketing",
    name: "Adobe Creative Cloud",
    category: "Creative tools",
    categoryAr: "الأدوات والبرمجيات الإبداعية",
    sector: "marketing",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "أدوات تصميم وإنتاج إبداعي",
    description: "Comprehensive vector identity, motion graphics, video post-production, and brand asset production.",
    descriptionAr: "تصميم الهويات الرقمية المتجهة والرسوم المتحركة والمونتاج وإنتاج الأصول البصرية المؤسسية.",
    website: "https://adobe.com",
    verificationStatus: false,
  },
  {
    id: "linkedin-marketing",
    name: "LinkedIn Marketing",
    category: "Social platforms",
    categoryAr: "منصات التواصل المهني",
    sector: "marketing",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "منصات الاستحواذ B2B",
    description: "Account-based B2B advertising, executive personal branding, and high-intent corporate lead acquisition.",
    descriptionAr: "إعلانات استهداف الحسابات B2B وبناء الحضور التنفيذي واستقطاب عملاء الشركات الكبرى.",
    website: "https://linkedin.com",
    verificationStatus: false,
  },
  {
    id: "tiktok-marketing",
    name: "TikTok Ads",
    category: "Advertising platforms",
    categoryAr: "منصات الإعلانات التفاعلية",
    sector: "marketing",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "منظومة إعلانات الفيديو",
    description: "High-velocity short-form creative testing, creator partnerships, and direct-response campaign scaling.",
    descriptionAr: "إنتاج واختبار محتوى الفيديو القصير السريع وإدارة حملات الاستجابة المباشرة.",
    website: "https://ads.tiktok.com",
    verificationStatus: false,
  },
  {
    id: "hubspot-marketing",
    name: "HubSpot",
    category: "Marketing automation",
    categoryAr: "أتمتة التسويق وإدارة العملاء",
    sector: "marketing",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "منصة تنفيذ وتكامل",
    description: "Inbound funnel automation, lifecycle email sequences, CRM data capture, and sales pipeline alignment.",
    descriptionAr: "أتمتة مسارات التسويق والبريد الإلكتروني ومزامنة بيانات العملاء مع فرق المبيعات.",
    website: "https://hubspot.com",
    verificationStatus: false,
  },
  {
    id: "mailchimp-marketing",
    name: "Mailchimp",
    category: "Marketing automation",
    categoryAr: "أتمتة التسويق والبريد",
    sector: "marketing",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "منصة تنفيذ وتكامل",
    description: "Audience segmentation, personalized retention drip sequences, and e-commerce transactional messaging.",
    descriptionAr: "تقسيم الجمهور وحملات الحفاظ على العملاء والرسائل المعاملاتية للمتاجر الإلكترونية.",
    website: "https://mailchimp.com",
    verificationStatus: false,
  },
  {
    id: "canva-marketing",
    name: "Canva Enterprise",
    category: "Creative tools",
    categoryAr: "أدوات تصميم القوالب المؤسسية",
    sector: "marketing",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "أدوات إنتاج ونشر القوالب",
    description: "Modular brand template system generation allowing internal client marketing teams to produce on-brand collateral.",
    descriptionAr: "بناء قوالب هوية مقيدة تتيح لفرق العميل الداخلية إنتاج المواد التسويقية مع الحفاظ على معايير العلامة.",
    website: "https://canva.com",
    verificationStatus: false,
  },

  // ── TECH ECOSYSTEM ──────────────────────────────────────────────────────────
  {
    id: "microsoft-tech",
    name: "Microsoft Azure",
    category: "Cloud infrastructure",
    categoryAr: "البنية السحابية",
    sector: "tech",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "بنية سحابية للبناء والتطوير",
    description: "Enterprise cloud application hosting, container services, hybrid infrastructure, and identity management.",
    descriptionAr: "استضافة التطبيقات المؤسسية، خدمات الحاويات، والبنية السحابية الهجينة وإدارة الهويات.",
    website: "https://azure.microsoft.com",
    verificationStatus: false,
  },
  {
    id: "aws-tech",
    name: "Amazon Web Services",
    category: "Cloud infrastructure",
    categoryAr: "البنية السحابية",
    sector: "tech",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "بنية سحابية للبناء والتطوير",
    description: "Scalable serverless microservices, distributed relational databases, edge caching, and automated deployment pipelines.",
    descriptionAr: "خدمات Microservices بدون خوادم، قواعد بيانات موزعة، وتوزيع المحتوى على الحافة.",
    website: "https://aws.amazon.com",
    verificationStatus: false,
  },
  {
    id: "gcp-tech",
    name: "Google Cloud Platform",
    category: "Cloud infrastructure",
    categoryAr: "البنية السحابية",
    sector: "tech",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "بنية سحابية للبناء والتطوير",
    description: "Kubernetes orchestration via GKE, BigQuery analytical storage, and low-latency global edge networks.",
    descriptionAr: "إدارة حاويات Kubernetes عبر GKE، والتخزين التحليلي BigQuery والشبكات العالمية فائقة السرعة.",
    website: "https://cloud.google.com",
    verificationStatus: false,
  },
  {
    id: "oracle-tech",
    name: "Oracle",
    category: "Enterprise platforms",
    categoryAr: "الأنظمة المؤسسية",
    sector: "tech",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "منصة تنفيذ وتكامل مؤسسي",
    description: "Enterprise database architecture, transactional reliability, and core ERP systems data synchronization.",
    descriptionAr: "معمارية قواعد البيانات المؤسسية ومزامنة بيانات أنظمة تخطيط الموارد الكبرى.",
    website: "https://oracle.com",
    verificationStatus: false,
  },
  {
    id: "sap-tech",
    name: "SAP",
    category: "Enterprise platforms",
    categoryAr: "الأنظمة المؤسسية",
    sector: "tech",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "منصة تنفيذ وتكامل مؤسسي",
    description: "Custom interface layer engineering and bi-directional API connections into existing SAP installations.",
    descriptionAr: "تطوير واجهات مخصصة وربط واجهات الـ API ثنائية الاتجاه مع أنظمة SAP المؤسسية.",
    website: "https://sap.com",
    verificationStatus: false,
  },
  {
    id: "odoo-tech",
    name: "Odoo",
    category: "Enterprise platforms",
    categoryAr: "الأنظمة المؤسسية",
    sector: "tech",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "تطبيق وتخصيص أنظمة Odoo",
    description: "Custom module development, business workflow digitization, inventory synchronization, and custom UI skins.",
    descriptionAr: "تطوير وحدات برمجية مخصصة، ورقمنة إجراءات العمل، وتكامل المخزون وواجهات استخدام عصرية.",
    website: "https://odoo.com",
    verificationStatus: false,
  },
  {
    id: "shopify-tech",
    name: "Shopify Plus",
    category: "Commerce platforms",
    categoryAr: "منصات التجارة الإلكترونية",
    sector: "tech",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "تطوير متاجر وتجارة مخصصة",
    description: "Headless e-commerce storefronts, custom checkout extensions, high-volume inventory sync, and ERP bridges.",
    descriptionAr: "متاجر تجارة إلكترونية مفصولة الرأس (Headless)، وتخصيص نقاط الدفع، وربط المخازن الضخمة مع أنظمة ERP.",
    website: "https://shopify.com",
    verificationStatus: false,
  },
  {
    id: "woocommerce-tech",
    name: "WooCommerce",
    category: "Commerce platforms",
    categoryAr: "منصات التجارة الإلكترونية",
    sector: "tech",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "تطوير وتكامل المتاجر",
    description: "Custom plugin architecture, high-concurrency payment gateway routing, and scalable WordPress stores.",
    descriptionAr: "بناء إضافات برمجية مخصصة وبوابات دفع عالية الأمان لمتاجر ووردبريس المتوسعة.",
    website: "https://woocommerce.com",
    verificationStatus: false,
  },
  {
    id: "github-tech",
    name: "GitHub",
    category: "Development technologies",
    categoryAr: "تقنيات التطوير والأتمتة",
    sector: "tech",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "أدوات التحكم والشيفرة",
    description: "Automated CI/CD workflows, vulnerability scanning, branch governance, and team deployment telemetry.",
    descriptionAr: "أتمتة خطوط النشر CI/CD وفحص الثغرات الأمنية التلقائي وإدارة الفروع البرمجية.",
    website: "https://github.com",
    verificationStatus: false,
  },
  {
    id: "cloudflare-tech",
    name: "Cloudflare",
    category: "Data and integration",
    categoryAr: "الأمان وشبكات التوصيل",
    sector: "tech",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "حماية وتسريع الأداء",
    description: "Edge caching, DDoS mitigation, serverless worker execution, and global DNS architecture.",
    descriptionAr: "تسريع التوصيل والحماية من هجمات DDoS وتشغيل البرمجيات على شبكة الحافة السريعة.",
    website: "https://cloudflare.com",
    verificationStatus: false,
  },

  // ── AI ECOSYSTEM ────────────────────────────────────────────────────────────
  {
    id: "openai-ai",
    name: "OpenAI",
    category: "AI model providers",
    categoryAr: "مزودو النماذج الذكية",
    sector: "ai",
    relationshipType: "Technology partner",
    relationshipTypeAr: "منظومة النماذج اللغوية",
    description: "GPT-4o and reasoning model API integration with structured outputs, function calling, and deterministic agents.",
    descriptionAr: "دمج نماذج GPT-4o المتقدمة مع مخرجات مهيكلة واستدعاء الدوال وبناء وكلاء حاسمين.",
    website: "https://openai.com",
    verificationStatus: false,
  },
  {
    id: "anthropic-ai",
    name: "Anthropic Claude",
    category: "AI model providers",
    categoryAr: "مزودو النماذج الذكية",
    sector: "ai",
    relationshipType: "Technology partner",
    relationshipTypeAr: "منظومة النماذج اللغوية",
    description: "Claude 3.5 Sonnet agent systems, complex multi-step reasoning, and high-precision document extraction.",
    descriptionAr: "أنظمة وكلاء تعتمد Claude 3.5 Sonnet للاستدلال متعدد الخطوات واستخراج بيانات الوثائق بدقة بالغة.",
    website: "https://anthropic.com",
    verificationStatus: false,
  },
  {
    id: "azure-ai",
    name: "Microsoft Azure AI",
    category: "Cloud AI",
    categoryAr: "الذكاء الاصطناعي السحابي المؤسسي",
    sector: "ai",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "بنية النماذج السحابية الخاصة",
    description: "Private enterprise model deployments with strict data residency, tenant isolation, and SOC 2 / HIPAA compliance.",
    descriptionAr: "نشر نماذج الذكاء الاصطناعي في بيئات سحابية خاصة تضمن عزل البيانات وحمايتها وفق معايير الامتثال.",
    website: "https://azure.microsoft.com/en-us/solutions/ai",
    verificationStatus: false,
  },
  {
    id: "aws-bedrock-ai",
    name: "AWS Bedrock",
    category: "Cloud AI",
    categoryAr: "الذكاء الاصطناعي السحابي المؤسسي",
    sector: "ai",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "بنية النماذج السحابية",
    description: "Multi-foundation model access with VPC endpoints, guardrails, and deterministic agent orchestration.",
    descriptionAr: "الوصول إلى نماذج تأسيسية متعددة عبر شبكات افتراضية خاصة مع تطبيق ضوابط الأمان.",
    website: "https://aws.amazon.com/bedrock",
    verificationStatus: false,
  },
  {
    id: "google-vertex-ai",
    name: "Google Cloud Vertex AI",
    category: "Cloud AI",
    categoryAr: "الذكاء الاصطناعي السحابي المؤسسي",
    sector: "ai",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "بنية النماذج السحابية",
    description: "Gemini multi-modal integration, automated ground-truth evaluation, and large context enterprise search.",
    descriptionAr: "تكامل نماذج Gemini متعددة الوسائط والبحث المؤسسي في السياقات الضخمة وتقييم دقة الإجابات.",
    website: "https://cloud.google.com/vertex-ai",
    verificationStatus: false,
  },
  {
    id: "nvidia-ai",
    name: "NVIDIA",
    category: "Private infrastructure",
    categoryAr: "البنية التحتية الخاصة والتسريع",
    sector: "ai",
    relationshipType: "Technology partner",
    relationshipTypeAr: "بنية الحوسبة والتسريع",
    description: "Optimized inference on dedicated GPU infrastructure for on-premise, air-gapped enterprise intelligence.",
    descriptionAr: "تسريع تشغيل النماذج محلياً على معالجات GPU مخصصة للمؤسسات التي تتطلب استقلالية تامة.",
    website: "https://nvidia.com",
    verificationStatus: false,
  },
  {
    id: "n8n-ai",
    name: "n8n Automation",
    category: "Automation",
    categoryAr: "منصات أتمتة المسارات",
    sector: "ai",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "منصة تنفيذ وأتمتة مسارات",
    description: "Self-hosted workflow automation, webhook triggers, API sync, and private agent tool-calling backends.",
    descriptionAr: "أتمتة المسارات الذاتية الاستضافة وربط الأنظمة عبر Webhooks واستدعاء أدوات الوكلاء المؤتمتة.",
    website: "https://n8n.io",
    verificationStatus: false,
  },
  {
    id: "huggingface-ai",
    name: "Hugging Face",
    category: "AI model providers",
    categoryAr: "نماذج الذكاء مفتوحة المصدر",
    sector: "ai",
    relationshipType: "Technology partner",
    relationshipTypeAr: "مكتبة النماذج المفتوحة",
    description: "Open-source fine-tuned models deployed inside client infrastructure for total governance and privacy.",
    descriptionAr: "نماذج مفتوحة المصدر مخصصة ومضبوطة بدقة تُنشر بالكامل داخل خوادم العميل لحماية الخصوصية.",
    website: "https://huggingface.co",
    verificationStatus: false,
  },
  {
    id: "vector-db-ai",
    name: "Pinecone & Qdrant",
    category: "Data and retrieval",
    categoryAr: "قواعد البيانات الشعاعية واسترجاع المعرفة",
    sector: "ai",
    relationshipType: "Implementation platform",
    relationshipTypeAr: "محركات استرجاع المعرفة RAG",
    description: "Low-latency vector databases for enterprise semantic search, document embeddings, and real-time knowledge retrieval.",
    descriptionAr: "قواعد بيانات شعاعية فائقة السرعة للبحث الدلالي واسترجاع المعرفة المؤسسية اللحظية.",
    website: "https://pinecone.io",
    verificationStatus: false,
  },

  // ── SYSTEM INTEGRATOR & CYBERSECURITY ECOSYSTEM ─────────────────────────────
  {
    id: "fortinet-cyber",
    name: "Fortinet",
    category: "Security",
    categoryAr: "الأمن السيبراني وجدران الحماية",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "منظومة حلول أمنية وتكامل",
    description: "Enterprise FortiGate Next-Generation Firewalls, FortiSwitch, FortiAP, and integrated Security Fabric implementations.",
    descriptionAr: "جدران حماية الجيل القادم FortiGate وشبكات FortiSwitch وحلول Security Fabric المترابطة.",
    website: "https://fortinet.com",
    featured: true,
    verificationStatus: false,
  },
  {
    id: "sophos-cyber",
    name: "Sophos",
    category: "Security",
    categoryAr: "الأمن السيبراني وحماية الأجهزة",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "منظومة الحماية الأمنية",
    description: "Intercept X endpoint security, synchronized threat protection, and automated ransomware mitigation.",
    descriptionAr: "حماية النقاط الطرفية المتقدمة والتصدي الاستباقي لبرمجيات الفدية والهجمات الموجهة.",
    website: "https://sophos.com",
    verificationStatus: false,
  },
  {
    id: "palo-alto-cyber",
    name: "Palo Alto Networks",
    category: "Security",
    categoryAr: "الأمن السيبراني المؤسسي",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "منظومة الحماية المتقدمة",
    description: "Zero-Trust enterprise architecture, Prisma Cloud security, and advanced cloud threat protection.",
    descriptionAr: "تطبيق معمارية انعدام الثقة Zero-Trust وحماية البيئات السحابية عبر Prisma Cloud.",
    website: "https://paloaltonetworks.com",
    verificationStatus: false,
  },
  {
    id: "microsoft-security-cyber",
    name: "Microsoft Security",
    category: "Security",
    categoryAr: "أمان السحابة وحماية الهويات",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "حلول الأمان السحابي",
    description: "Microsoft Defender for Endpoint, Entra ID zero-trust identity, and Microsoft Sentinel SIEM/SOAR.",
    descriptionAr: "حماية النقاط الطرفية عبر Defender وإدارة الهويات عبر Entra ID وحلول Sentinel SIEM.",
    website: "https://microsoft.com/security",
    verificationStatus: false,
  },
  {
    id: "cisco-cyber",
    name: "Cisco",
    category: "Network",
    categoryAr: "الشبكات والربط المؤسسي",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "أنظمة الشبكات والتوجيه",
    description: "Enterprise Catalyst switching, SD-WAN branch interconnection, Meraki wireless, and campus network design.",
    descriptionAr: "محولات شبكات Catalyst وربط الفروع عبر SD-WAN وشبكات Meraki اللاسلكية المؤسسية.",
    website: "https://cisco.com",
    verificationStatus: false,
  },
  {
    id: "aruba-cyber",
    name: "HPE Aruba Networking",
    category: "Network",
    categoryAr: "الشبكات والربط المؤسسي",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "شبكات مؤسسية ولاسلكية",
    description: "High-density enterprise Wi-Fi 6E/7, edge security switching, and centralized ClearPass network access control.",
    descriptionAr: "شبكات Wi-Fi 6E/7 عالية الكثافة ومحولات شبكية وإدارة تصاريح الدخول عبر ClearPass.",
    website: "https://arubanetworks.com",
    verificationStatus: false,
  },
  {
    id: "teams-cyber",
    name: "Microsoft Teams",
    category: "VoIP and collaboration",
    categoryAr: "الاتصالات الموحدة وقاعات الاجتماع",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "حلول الاتصالات وقاعات العمل",
    description: "Enterprise voice Direct Routing, Microsoft Teams Rooms smart hardware integration, and hybrid workspace design.",
    descriptionAr: "الربط الصوتي المؤسسي Direct Routing وتجهيز قاعات Microsoft Teams Rooms الذكية.",
    website: "https://teams.microsoft.com",
    verificationStatus: false,
  },
  {
    id: "avaya-cyber",
    name: "Avaya",
    category: "VoIP and collaboration",
    categoryAr: "الاتصالات الموحدة ومراكز الاتصال",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "أنظمة المقاسم ومراكز الاتصال",
    description: "Enterprise IP telephony, omni-channel contact centre routing, and high-reliability PBX voice systems.",
    descriptionAr: "مقاسم هاتفية IP متطورة ومراكز اتصال متعددة القنوات وحلول الاتصال الصوتي عالي الاعتمادية.",
    website: "https://avaya.com",
    verificationStatus: false,
  },
  {
    id: "yealink-cyber",
    name: "Yealink",
    category: "VoIP and collaboration",
    categoryAr: "أجهزة الاتصال وقاعات الاجتماعات",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "تجهيزات المؤتمرات الذكية",
    description: "Executive IP desk phones, certified Microsoft Teams room video bars, and board room conferencing systems.",
    descriptionAr: "هواتف مكتبية ذكية وأجهزة مؤتمرات فيديو معتمدة لقاعات الاجتماعات ومجالس الإدارة.",
    website: "https://yealink.com",
    verificationStatus: false,
  },
  {
    id: "dell-cyber",
    name: "Dell Technologies",
    category: "Data centre",
    categoryAr: "مراكز البيانات والخوادم",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "خوادم وحلول تخزين مؤسسية",
    description: "PowerEdge rack servers, PowerStore SAN/NAS storage arrays, and hyper-converged infrastructure (HCI).",
    descriptionAr: "خوادم PowerEdge ومصفوفات التخزين PowerStore وحلول البنية التحتية المتقاربة HCI.",
    website: "https://dell.com",
    verificationStatus: false,
  },
  {
    id: "hpe-cyber",
    name: "HPE",
    category: "Data centre",
    categoryAr: "مراكز البيانات والخوادم",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "خوادم وحلول تخزين مؤسسية",
    description: "ProLiant enterprise compute nodes, Alletra storage arrays, and mission-critical datacenter infrastructure.",
    descriptionAr: "خوادم ProLiant فائقة الاعتمادية ومصفوفات التخزين Alletra للبنى التحتية الحرجة.",
    website: "https://hpe.com",
    verificationStatus: false,
  },
  {
    id: "lenovo-cyber",
    name: "Lenovo ThinkSystem",
    category: "Data centre",
    categoryAr: "مراكز البيانات والخوادم",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "خوادم وحلول تخزين مؤسسية",
    description: "High-density enterprise server racks, multi-node clustering, and scalable enterprise virtualization compute.",
    descriptionAr: "خوادم حوسبة عالية الكثافة وأنظمة تشغيل خوادم افتراضية قابلة للتوسع.",
    website: "https://lenovo.com",
    verificationStatus: false,
  },
  {
    id: "vmware-cyber",
    name: "VMware by Broadcom",
    category: "Data centre",
    categoryAr: "البيئات الافتراضية والسحابة الخاصة",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "برمجيات الحوسبة الافتراضية",
    description: "vSphere virtualization, vSAN software-defined storage, and private cloud software deployment.",
    descriptionAr: "بيئات vSphere الافتراضية والتخزين البرمجي vSAN وبناء السحب الخاصة للمؤسسات.",
    website: "https://vmware.com",
    verificationStatus: false,
  },
  {
    id: "veeam-cyber",
    name: "Veeam",
    category: "Data centre",
    categoryAr: "النسخ الاحتياطي والتعافي من الكوارث",
    sector: "system-integrator-cybersecurity",
    relationshipType: "Vendor ecosystem",
    relationshipTypeAr: "حلول النسخ الاحتياطي والتعافي",
    description: "Automated ransomware-proof backups, disaster recovery orchestration, and near-zero RTO/RPO enterprise replication.",
    descriptionAr: "نسخ احتياطي منيع ضد الفيروسات وإدارة خطط التعافي من الكوارث مع أدنى زمن استرجاع RTO.",
    website: "https://veeam.com",
    verificationStatus: false,
  },

  // ── HUB ECOSYSTEM ───────────────────────────────────────────────────────────
  {
    id: "m365-hub",
    name: "Microsoft 365",
    category: "Productivity",
    categoryAr: "الإنتاجية المؤسسية",
    sector: "hub",
    relationshipType: "Integration",
    relationshipTypeAr: "تكامل وتوافق الأنظمة",
    description: "Single Sign-On (SSO), Outlook calendar task syncing, and SharePoint corporate file storage bridge.",
    descriptionAr: "تسجيل الدخول الموحد SSO ومزامنة تقاويم Outlook وربط الملفات مع SharePoint.",
    website: "https://microsoft.com/microsoft-365",
    verificationStatus: false,
  },
  {
    id: "workspace-hub",
    name: "Google Workspace",
    category: "Productivity",
    categoryAr: "الإنتاجية المؤسسية",
    sector: "hub",
    relationshipType: "Integration",
    relationshipTypeAr: "تكامل وتوافق الأنظمة",
    description: "Google Meet scheduling, Google Drive document attachment, and OAuth authentication pipelines.",
    descriptionAr: "جدولة اجتماعات Google Meet ومزامنة المستندات وتأمين تسجيل الدخول عبر OAuth.",
    website: "https://workspace.google.com",
    verificationStatus: false,
  },
  {
    id: "shopify-hub",
    name: "Shopify",
    category: "Commerce",
    categoryAr: "التجارة الإلكترونية والمتاجر",
    sector: "hub",
    relationshipType: "Integration",
    relationshipTypeAr: "تكامل المبيعات والمخزون",
    description: "Live order streaming, centralized multi-branch inventory balance, and automated sales commission tracking.",
    descriptionAr: "مزامنة لحظية للطلبات وإدارة المخزون متعدد الفروع واحتساب عمولات المبيعات تلقائياً.",
    website: "https://shopify.com",
    verificationStatus: false,
  },
  {
    id: "woocommerce-hub",
    name: "WooCommerce",
    category: "Commerce",
    categoryAr: "التجارة الإلكترونية والمتاجر",
    sector: "hub",
    relationshipType: "Integration",
    relationshipTypeAr: "تكامل المبيعات والمخزون",
    description: "Two-way product catalogue synchronization, payment confirmation webhook feeds, and customer sync.",
    descriptionAr: "مزامنة ثنائية لكتالوج المنتجات وتأكيد الدفع عبر Webhooks ودمج بيانات العملاء.",
    website: "https://woocommerce.com",
    verificationStatus: false,
  },
  {
    id: "stripe-hub",
    name: "Stripe",
    category: "Payments",
    categoryAr: "المدفوعات الإلكترونية والفواتير",
    sector: "hub",
    relationshipType: "Integration",
    relationshipTypeAr: "بوابات الدفع والاشتراكات",
    description: "Automated recurring subscription billing, localized credit card checkout, and multi-currency payout reconciliation.",
    descriptionAr: "فواتير الاشتراكات الدورية المؤتمتة والدفع بالبطاقات المصرفية وتسوية العملات المتعددة.",
    website: "https://stripe.com",
    verificationStatus: false,
  },
  {
    id: "slack-hub",
    name: "Slack",
    category: "Communications",
    categoryAr: "التواصل الداخلي والإشعارات",
    sector: "hub",
    relationshipType: "Integration",
    relationshipTypeAr: "إشعارات العمليات الفورية",
    description: "Real-time deal milestone alerts, approval request webhooks, and client ticket escalation channels.",
    descriptionAr: "تنبيهات فورية لصفقات المبيعات وطلبات الاعتماد وتصعيد تذاكر الدعم إلى قنوات العمل.",
    website: "https://slack.com",
    verificationStatus: false,
  },
  {
    id: "quickbooks-hub",
    name: "QuickBooks",
    category: "Accounting",
    categoryAr: "المحاسبة والمالية",
    sector: "hub",
    relationshipType: "Integration",
    relationshipTypeAr: "الربط المحاسبي التلقائي",
    description: "General ledger entry sync, tax reconciliation, automated accounts receivable, and invoice payment matching.",
    descriptionAr: "مزامنة قيود اليومية المحاسبية واحتساب الضرائب وتسوية الفواتير ومطابقة المدفوعات.",
    website: "https://quickbooks.intuit.com",
    verificationStatus: false,
  },
  {
    id: "xero-hub",
    name: "Xero",
    category: "Accounting",
    categoryAr: "المحاسبة والمالية",
    sector: "hub",
    relationshipType: "Integration",
    relationshipTypeAr: "الربط المحاسبي التلقائي",
    description: "Continuous bank feed integration, supplier invoice reconciliation, and profit & loss statement syncing.",
    descriptionAr: "الربط البنكي المستمر ومطابقة فواتير الموردين وتحديث تقارير الأرباح والخسائر.",
    website: "https://xero.com",
    verificationStatus: false,
  },
]
