export interface SectorDefinition {
  id: string
  name: string
  nameAr: string
  fullName: string
  fullNameAr: string
  slug: string
  canonicalHref: string
  legacyHref: string
  color: string
  tint: string
  index: string
  headline: string
  headlineAr: string
  tagline: string
  taglineAr: string
  description: string
  descriptionAr: string
  services: string[]
  servicesAr: string[]
  finalCtaHeadline: string
  finalCtaHeadlineAr: string
  finalCtaDesc: string
  finalCtaDescAr: string
  heroBreadcrumb: string
  iconSrc: string
  heroImage?: string
}

export const SECTORS: SectorDefinition[] = [
  {
    id: "saas",
    name: "SaaS",
    nameAr: "البرمجيات كخدمة",
    fullName: "Growl SaaS",
    fullNameAr: "جرول للبرمجيات كخدمة",
    slug: "saas",
    canonicalHref: "/sectors/saas",
    legacyHref: "/divisions/saas",
    color: "#FBE858",
    tint: "#FBF1AA",
    index: "01",
    headline: "The System Without the Project",
    headlineAr: "النظام المتكامل دون مخاطر التأسيس",
    tagline: "Subscription Enterprise Systems",
    taglineAr: "أنظمة مؤسسية باشتراكات دورية",
    description: "Enterprise systems re-engineered as subscription products. The same system, without the timeline or the capital.",
    descriptionAr: "أنظمة مؤسسية أعيدت هندستها كمنتجات اشتراك جاهزة. نفس الكفاءة دون استهلاك الوقت ورأس المال.",
    services: [
      "Defined Subscription Products",
      "Accelerated Zero-Friction Onboarding",
      "Fully Managed Security & Platform Updates",
      "Modular Elastic Capability Expansion",
      "Predictable Operational OpEx & Enterprise SLA",
    ],
    servicesAr: [
      "باقات اشتراك مؤسسية واضحة المعالم",
      "تهيئة وتشغيل فوري دون تعقيدات النشر",
      "إدارة وصيانة وتحديثات أمنية مستمرة",
      "توسيع الوحدات والمقاعد بمرونة تامة",
      "تكاليف تشغيلية متوقعة واتفاقيات مستوى خدمة SLA",
    ],
    finalCtaHeadline: "Start with the system your business needs.",
    finalCtaHeadlineAr: "ابدأ بالنظام الذي تحتاجه أعمالك اليوم",
    finalCtaDesc: "Subscribe to enterprise-grade software products with predictable monthly or annual billing, rapid onboarding, and fully managed continuous updates.",
    finalCtaDescAr: "اشترك في برمجيات مؤسسية جاهزة بفواتير شهرية أو سنوية واضحة، وتهيئة سريعة، ودعم فني مستمر.",
    heroBreadcrumb: "Sectors / SaaS",
    iconSrc: "/growl-icons/growl-saas.png",
    heroImage: "/images/sectors/saas-hero.webp",
  },
  {
    id: "tech",
    name: "Tech",
    nameAr: "التقنية والبرمجيات",
    fullName: "Growl Tech",
    fullNameAr: "جرول للتقنية وهندسة البرمجيات",
    slug: "tech",
    canonicalHref: "/sectors/tech",
    legacyHref: "/divisions/technology",
    color: "#FF7A00",
    tint: "#FCCA9C",
    index: "02",
    headline: "Software That Runs the Business",
    headlineAr: "برمجيات مؤسسية تدير صلب الأعمال",
    tagline: "Software & Engineering Stack",
    taglineAr: "هندسة البرمجيات المؤسسية",
    description: "Web, mobile and enterprise systems - built from scratch, or implemented on the platform you already chose.",
    descriptionAr: "أنظمة ويب وهواتف وحلول مؤسسية — تُبنى من الصفر أو تُنفذ على المنصات والأنظمة التي اعتمدتموها.",
    services: [
      "Mobile Applications (iOS, Android, Cross-Platform)",
      "Web Development (Custom Platforms & Enterprise Portals)",
      "E-commerce (Shopify, WooCommerce, Headless Systems)",
      "Enterprise Systems (ERP, CRM, POS & HR)",
      "Platform Implementation (Odoo, Oracle, SAP)",
      "Private Solutions (Bespoke Systems & Automation)",
    ],
    servicesAr: [
      "تطبيقات الهواتف الذكية (iOS و Android وتطبيقات هجينة)",
      "تطوير منصات الويب والبوابات المؤسسية الكبرى",
      "التجارة الإلكترونية المتقدمة والتكامل اللوجستي",
      "الأنظمة المؤسسية (ERP و CRM ونقاط البيع POS)",
      "تطبيق وتخصيص المنصات العالمية (Odoo و SAP)",
      "الحلول البرمجية الخاصة والمسارات الآمنة",
    ],
    finalCtaHeadline: "Build the software your operation actually needs.",
    finalCtaHeadlineAr: "ابنِ البرمجيات التي تحتاجها عملياتك التشغيلية",
    finalCtaDesc: "Deploy high-performance web platforms, native mobile applications, and enterprise microservices engineered for continuous uptime and scalability.",
    finalCtaDescAr: "أطلق منصات ويب متقدمة وتطبيقات هواتف ذكية وبنية سحابية مصممة للعمل دون توقف وقابلة للتوسع الفوري.",
    heroBreadcrumb: "Sectors / Tech",
    iconSrc: "/growl-icons/growl-tech.png",
    heroImage: "/images/sectors/tech-hero.webp",
  },
  {
    id: "hub",
    name: "Hub",
    nameAr: "منصة جرول هب",
    fullName: "Growl Hub",
    fullNameAr: "جرول هب للمنتجات السحابية",
    slug: "hub",
    canonicalHref: "/sectors/hub",
    legacyHref: "/divisions/hub",
    color: "#1F6FEB",
    tint: "#A3C3F5",
    index: "03",
    headline: "The Connected Operating Suite",
    headlineAr: "المنظومة السحابية المتكاملة لإدارة الأعمال",
    tagline: "Cloud ERP, CRM, POS & Management Systems",
    taglineAr: "الأنظمة السحابية المتكاملة وإدارة الأعمال",
    description: "Pre-integrated modular business platforms for operations, multi-location retail, financial pipelines, and enterprise workforce management.",
    descriptionAr: "أنظمة تشغيلية متكاملة ومترابطة لإدارة العمليات، المبيعات متعددة الفروع، الرقابة المالية، والموارد البشرية.",
    services: [
      "ERP (Operations, Inventory, Procurement & Finance)",
      "CRM (Pipelines, Accounts, Contacts & Forecasting)",
      "POS (Retail Sales, Multi-Branch & Real-Time Sync)",
      "Management Systems (HR, Attendance & Workflows)",
      "Direct API Integration with Regional Gateways",
    ],
    servicesAr: [
      "نظام ERP (العمليات، المخازن، المشتريات والمالية)",
      "نظام CRM (مسارات المبيعات، الحسابات والتنبؤات)",
      "نظام POS (نقاط البيع السحابية والمزامنة اللحظية)",
      "أنظمة الإدارة (الموارد البشرية، الحضور وسير العمل)",
      "ربط برمجي مباشر مع بوابات الدفع والخدمات الإقليمية",
    ],
    finalCtaHeadline: "Find the right system for your operation.",
    finalCtaHeadlineAr: "اختر النظام الأنسب لعملياتك التشغيلية",
    finalCtaDesc: "Scale ERP, CRM, POS, and workforce operations seamlessly with enterprise-grade subscription software that deploys in days, not quarters.",
    finalCtaDescAr: "طوّر عمليات الـ ERP و CRM ونقاط البيع وإدارة الفرق عبر برمجيات اشتراك مؤسسية تُنشر خلال أيام معدودة.",
    heroBreadcrumb: "Sectors / Hub",
    iconSrc: "/growl-icons/growl-hub.png",
    heroImage: "/images/sectors/hub-hero.webp",
  },
  {
    id: "system-integrator-cybersecurity",
    name: "System Integrator & Cybersecurity",
    nameAr: "تكامل الأنظمة والأمن السيبراني",
    fullName: "Growl System Integrator & Cybersecurity",
    fullNameAr: "جرول لتكامل الأنظمة والأمن السيبراني",
    slug: "system-integrator-cybersecurity",
    canonicalHref: "/sectors/system-integrator-cybersecurity",
    legacyHref: "/divisions/cybersecurity",
    color: "#DA291C",
    tint: "#F1ACA7",
    index: "04",
    headline: "The Infrastructure Behind the Business",
    headlineAr: "البنية التحتية الصلبة خلف استقرار الأعمال",
    tagline: "Enterprise Security & Infrastructure",
    taglineAr: "الأمن السيبراني والبنية التحتية",
    description: "Security, network, collaboration and data centre - vendor-certified, tender-ready, built to renew.",
    descriptionAr: "الأمن السيبراني، الشبكات المؤسسية، الاتصالات الموحدة ومراكز البيانات — متوافقة مع المناقصات ومصممة للاستدامة.",
    services: [
      "Security (Next-Gen Firewalls, ZTNA, Endpoint, SOC)",
      "Network (Switching, Routing, SD-WAN, Enterprise WiFi)",
      "VoIP & Collaboration (IP Telephony, Smart Rooms, Teams)",
      "Data Centre (Servers, Storage, Virtualization, Backup)",
      "Site Assessments, Tender BoQ & Renewal Support",
    ],
    servicesAr: [
      "الأمن السيبراني (جدران الحماية، شبكات ZTNA، أمان النقاط)",
      "الشبكات المؤسسية (المحولات، شبكات SD-WAN، الربط اللاسلكي)",
      "الاتصالات الموحدة (هواتف IP، غرف الاجتماعات الذكية)",
      "مراكز البيانات (الخوادم، التخزين، الافتراضية، النسخ الاحتياطي)",
      "تقييم المواقع الميداني، جداول الكميات ودعم التجديدات",
    ],
    finalCtaHeadline: "Plan the infrastructure your business depends on.",
    finalCtaHeadlineAr: "خطط للبنية التحتية التي تعتمد عليها أعمالك",
    finalCtaDesc: "Engage our vendor-certified engineers for tender-ready network architectures, zero-trust perimeter defense, and resilient datacenter systems.",
    finalCtaDescAr: "تعاون مع مهندسينا المعتمدين لتصميم وتنفيذ شبكات جاهزة للمناقصات وحماية أمنية صفرية ومراكز بيانات عالية التوافر.",
    heroBreadcrumb: "Sectors / System Integrator & Cybersecurity",
    iconSrc: "/growl-icons/growl-cyber.png",
    heroImage: "/images/sectors/cyber-hero.webp",
  },
  {
    id: "ai",
    name: "AI",
    nameAr: "الذكاء الاصطناعي والأتمتة",
    fullName: "Growl AI",
    fullNameAr: "جرول للذكاء الاصطناعي",
    slug: "ai",
    canonicalHref: "/sectors/ai",
    legacyHref: "/divisions/ai",
    color: "#0FCFC0",
    tint: "#A2F6EF",
    index: "05",
    headline: "Automation Sold as a Product",
    headlineAr: "أتمتة ذكية تباع كمنتج محدد النطاق",
    tagline: "Autonomous AI & Automation",
    taglineAr: "الأتمتة والوكلاء الأذكياء",
    description: "Fixed scope, fixed price, deployed on your own systems. Not consulting hours.",
    descriptionAr: "نطاق عمل محدد، سعر ثابت، ونشر مباشر على أنظمتكم الخاصة. ليس ساعات استشارية مفتوحة.",
    services: [
      "AI Automation (Production n8n Workflow Engines)",
      "Agentic AI (Autonomous Tool-Connected Agents via MCP)",
      "Internal AI Solutions (Private On-Premise LLMs & RAG)",
      "Intelligent Document Processing (OCR & Entity Extraction)",
      "Human-in-the-Loop Governance & Audit Logging",
    ],
    servicesAr: [
      "أتمتة مسارات العمل المؤسسية عبر محركات n8n",
      "الوكلاء المستقلون المتصلون بالأدوات عبر بروتوكول MCP",
      "حلول الذكاء الاصطناعي الخاصة واسترجاع الوثائق RAG",
      "المعالجة الذكية للوثائق والمستندات واستخراج البيانات",
      "حوكمة التدخل البشري وسجلات التدقيق الصارمة",
    ],
    finalCtaHeadline: "Turn repeatable work into a reliable system.",
    finalCtaHeadlineAr: "حوّل المهام المتكررة إلى نظام آلي موثوق",
    finalCtaDesc: "Implement deterministic multi-agent systems, secure private LLM infrastructure, and MCP-connected workflows without recurring consultant overhead.",
    finalCtaDescAr: "طبّق منظومات وكلاء أذكياء وبنية نماذج لغوية خاصة وبروتوكولات MCP متصلة دون تكاليف استشارات مستمرة.",
    heroBreadcrumb: "Sectors / AI",
    iconSrc: "/growl-icons/growl-ai icon.png",
    heroImage: "/images/sectors/ai-hero.webp",
  },
  {
    id: "marketing",
    name: "Marketing & Branding",
    nameAr: "التسويق وبناء العلامات",
    fullName: "Growl Marketing & Branding",
    fullNameAr: "جرول للتسويق وبناء العلامات",
    slug: "marketing",
    canonicalHref: "/sectors/marketing",
    legacyHref: "/divisions/marketing",
    color: "#E5389A",
    tint: "#F1A7D1",
    index: "06",
    headline: "Brands That Earn Attention",
    headlineAr: "علامات تجارية تكتسب الاهتمام والريادة",
    tagline: "Brand & Media Architecture",
    taglineAr: "هندسة العلامة والوسائط",
    description: "Identity, campaigns and media production for businesses that need to be seen, understood and chosen.",
    descriptionAr: "هوية استراتيجية، حملات تسويقية وإنتاج إعلامي متكامل للشركات التي تختار الظهور والريادة.",
    services: [
      "Brand Identity Systems & Design Tokens",
      "Visual Guidelines & Print Production",
      "Multi-Channel Campaign Strategy & Paid Media",
      "Studio Video Production & Motion Graphics",
      "Conversion Tracking & Attribution Telemetry",
    ],
    servicesAr: [
      "أنظمة الهوية البصرية المتكاملة ومحددات التصميم",
      "أدلة العلامة ومواصفات الإنتاج الطباعي والميداني",
      "استراتيجية الحملات الإعلانية متعددة القنوات",
      "الإنتاج المرئي السينمائي والموشن جرافيكس",
      "تتبع التحويل ونماذج الإسناد الرقمي الدقيقة",
    ],
    finalCtaHeadline: "Build a Brand People Choose",
    finalCtaHeadlineAr: "ابنِ علامة تجارية يختارها الجمهور",
    finalCtaDesc: "Partner with Growl Marketing & Branding to define your category narrative and execute campaigns that drive verifiable customer acquisition.",
    finalCtaDescAr: "تعاون مع فريق جرول للتسويق وبناء العلامات لصياغة سردية تنافسية وإطلاق حملات استحواذ رقمية مثبتة العائد.",
    heroBreadcrumb: "Sectors / Marketing & Branding",
    iconSrc: "/growl-icons/growl-marketing.png",
  },
]
